routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ArtistsController@index');

Auth::routes();

Route::resource('/artists', 'ArtistsController');
Route::resource('/albums', 'AlbumsController');

app/Album.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Album extends Model
{
    public function artist() {
        return $this->belongsTo('App\Artist');
    }
}

app/Artist.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Artist extends Model
{
    public function albums() {
        return $this->hasMany('App\Album');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AlbumsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Album;
use App\Artist;

class AlbumsController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $albums = Album::orderBy('updated_at', 'desc')->get();
        return view('albums.index')->with('albums', $albums);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $artists = Artist::all();
        return view('albums.create')->with('artists', $artists);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'artist_id' => 'required',
            'year' => 'required|numeric',
        ]);
        
        $album = new Album();
        $album->title = $request->input('title');
        $album->artist_id = $request->input('artist_id');
        $album->year = $request->input('year');
        $album->save();

        return redirect('/albums')->with('success', 'Album created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $album = Album::find($id);
        $artists = Artist::all();
        $dados = array(
            "album" => $album,
            'artists' => $artists
        );

        return view('albums.edit')->with('dados', $dados);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'artist_id' => 'required',
            'year' => 'required',
        ]);
        
        $album = Album::find($id);
        $album->title = $request->input('title');
        $album->artist_id = $request->input('artist_id');
        $album->year = $request->input('year');
        $album->save();

        return redirect('/albums')->with('success', 'Album updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $album = Album::find($id);
        $album->delete();
        return redirect('/albums')->with('success', 'Album deleted');
    }
}

app/Http/Controllers/ArtistsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Artist;
use App\Album;

class ArtistsController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $artists = Artist::orderBy('updated_at', 'desc')->get();
        return view('artists.index')->with('artists', $artists);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('artists.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'twitter' => 'required',
        ]);
        
        $artist = new Artist();
        $artist->name = $request->input('name');
        $artist->twitter = $request->input('twitter');
        $artist->save();

        return redirect('/artists')->with('success', 'Artist created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $artist = Artist::find($id);
        return view('artists.edit')->with('artist', $artist);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'twitter' => 'required',
        ]);
        
        $artist = Artist::find($id);
        $artist->name = $request->input('name');
        $artist->twitter = $request->input('twitter');
        $artist->save();

        return redirect('/artists')->with('success', 'Artist updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $artist = Artist::find($id);
        $albums = Album::where('artist_id', $id);
        $albums->delete();
        $artist->delete();
        return redirect('/artists')->with('success', 'Artist deleted');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/albums/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @include('messages')
        <h1>Add new Album</h1>
        <form method="post" action="{{ route('albums.store') }}">
            <div class="form-group">
                @csrf            
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title">
            </div>
            <div class="form-group">
                <label for="artist_id">Artist</label>
                <select class="form-control" name="artist_id">
                    <option value="">Select an artist</option>
                    @foreach ($artists as $artist)
                    <option value="{{$artist->id}}">{{$artist->name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="year">Year</label>
                <input type="text" class="form-control" name="year">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="{{ config('app.url') }}/albums" class="btn btn-outline-dark">Go Back</a>
        </form>
    </div>
@endsection

resources/views/albums/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @include('messages')
        <h1>Edit Album</h1>
        <form method="post" action="{{ route('albums.update', $dados['album']->id) }}">
            <div class="form-group">
                @method('PUT')
                @csrf
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title" value="{{$dados['album']->title}}">
            </div>
            <div class="form-group">
                <label for="artist_id">Artist</label>
                <select class="form-control" name="artist_id">
                    <option value="">Select an artist</option>
                    @foreach ($dados['artists'] as $artist)
                    <option
                        value="{{$artist->id}}"
                        {{($dados['album']->artist_id == $artist->id ? 'selected' : '')}}>
                        {{$artist->name}}
                    </option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="year">Year</label>
                <input type="text" class="form-control" name="year" value="{{$dados['album']->year}}">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="{{ config('app.url') }}/albums" class="btn btn-outline-dark">Go Back</a>
        </form>
    </div>
@endsection

resources/views/albums/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include('messages')
    <h1>Albums<a class="btn btn-primary float-right" href="{{config('app.url')}}/albums/create">Add New Album</a></h1>
    
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Album</th>
                <th scope="col">Artist</th>
                <th scope="col">Year</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($albums as $album)
            <tr>
                <th scope="row">{{$album->id}}</th>
                <td>{{$album->title}}</td>
                <td>{{$album->artist->name}}</td>
                <td>{{$album->year}}</td>
                <td>
                    <form action="{{ route('albums.destroy',$album->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <a class="btn btn-outline-dark" href="{{config('app.url')}}/albums/{{$album->id}}/edit">Edit</a>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/artists/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Add new Artist</h1>
        <form method="post" action="{{ route('artists.store') }}">
            <div class="form-group">
                @csrf            
                <label for="name">Name</label>
                <input type="text" class="form-control" name="name">
            </div>
            <div class="form-group">
                <label for="twitter">Twitter Handle</label>
                <input type="text" class="form-control" name="twitter">
                <small class="text-secondary">Without the '@' sign</small>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="{{ config('app.url') }}/artists" class="btn btn-outline-dark">Go Back</a>
        </form>
    </div>
@endsection

resources/views/artists/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Edit Artist</h1>
        <form method="post" action="{{ route('artists.update', $artist->id) }}">
            <div class="form-group">
                @method('PUT')
                @csrf            
                <label for="name">Name</label>
                <input type="text" class="form-control" name="name" value="{{$artist->name}}">
            </div>
            <div class="form-group">
                <label for="twitter">Twitter Handle</label>
                <input type="text" class="form-control" name="twitter" value="{{$artist->twitter}}">
                <small class="text-secondary">Without the '@' sign</small>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="{{ config('app.url') }}/artists" class="btn btn-outline-dark">Go Back</a>
        </form>
    </div>
@endsection

resources/views/artists/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include('messages')
    <h1>Artists <a class="btn btn-primary float-right" href="{{config('app.url')}}/artists/create">Add New Artist</a></h1>
    
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Artist</th>
                <th scope="col">Twitter Handle</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($artists as $artist)
            <tr>
                <th scope="row">{{$artist->id}}</th>
                <td>{{$artist->name}}</td>
                <td>
                    <a href="https://twitter.com/{{$artist->twitter}}" target="_blank">{{"@".$artist->twitter}}</a>
                </td>
                <td>
                    <form action="{{ route('artists.destroy',$artist->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <a class="btn btn-outline-dark" href="{{config('app.url')}}/artists/{{$artist->id}}/edit">Edit</a>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item"><a href="{{ config('app.url') }}/artists" class="nav-link">Artists</a></li>
                            <li class="nav-item"><a href="{{ config('app.url') }}/albums" class="nav-link">Albums</a></li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/messages.blade.php
@if (count($errors) > 0)
    @foreach ($errors->all() as $error)
        <div class="alert alert-danger">
            {{$error}}
        </div>
    @endforeach
@endif

@if (session('success'))
    <div class="alert alert-success">
        {{session('success')}}
    </div>
@endif

@if (session('error'))
    <div class="alert alert-danger">
        {{session('error')}}
    </div>
@endif